// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBswE2T-dotvzquPewAWrpi05aMg0RmAYw',
    appId: '1:597393642223:web:83b4cf96db543fb825c11a',
    messagingSenderId: '597393642223',
    projectId: 'gene-tree-prod',
    authDomain: 'gene-tree-prod.firebaseapp.com',
    storageBucket: 'gene-tree-prod.appspot.com',
    measurementId: 'G-V0EMX6FXY3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAT7L7KQg2PAH2JxWXAJs2KZDyz7daW63s',
    appId: '1:597393642223:android:b52da3d65a8e8b5a25c11a',
    messagingSenderId: '597393642223',
    projectId: 'gene-tree-prod',
    storageBucket: 'gene-tree-prod.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7PxOYWE67NkntFxxaGhjPe25oBEw8LA0',
    appId: '1:597393642223:ios:3f5d7a23b5d1feb725c11a',
    messagingSenderId: '597393642223',
    projectId: 'gene-tree-prod',
    storageBucket: 'gene-tree-prod.appspot.com',
    iosBundleId: 'com.aigenetreemobile.prod',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7PxOYWE67NkntFxxaGhjPe25oBEw8LA0',
    appId: '1:597393642223:ios:69061e437354f2ca25c11a',
    messagingSenderId: '597393642223',
    projectId: 'gene-tree-prod',
    storageBucket: 'gene-tree-prod.appspot.com',
    iosBundleId: 'com.example.geneTreeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBswE2T-dotvzquPewAWrpi05aMg0RmAYw',
    appId: '1:597393642223:web:1d7d4af9f2614c4d25c11a',
    messagingSenderId: '597393642223',
    projectId: 'gene-tree-prod',
    authDomain: 'gene-tree-prod.firebaseapp.com',
    storageBucket: 'gene-tree-prod.appspot.com',
    measurementId: 'G-TRTGVJ1TVP',
  );
}
