// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnSLdd940CILXsPpCBV39WQE2wgglfH5k',
    appId: '1:253222200495:web:b39ee10fa118589061605a',
    messagingSenderId: '253222200495',
    projectId: 'gene-tree-dev-2e250',
    authDomain: 'gene-tree-dev-2e250.firebaseapp.com',
    storageBucket: 'gene-tree-dev-2e250.appspot.com',
    measurementId: 'G-6PHYG1PB74',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBy2DZyGNJDX5fTKbWFDuFbz0gulPs2T18',
    appId: '1:253222200495:android:3b258e06311ebfcc61605a',
    messagingSenderId: '253222200495',
    projectId: 'gene-tree-dev-2e250',
    storageBucket: 'gene-tree-dev-2e250.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_Mv9ILMErxq4Jf9d1M1iuXEl-k-M0Udc',
    appId: '1:253222200495:ios:2019899f4fd3281061605a',
    messagingSenderId: '253222200495',
    projectId: 'gene-tree-dev-2e250',
    storageBucket: 'gene-tree-dev-2e250.appspot.com',
    iosBundleId: 'com.aigenetreemobile.dev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_Mv9ILMErxq4Jf9d1M1iuXEl-k-M0Udc',
    appId: '1:253222200495:ios:345e7a85af686e5961605a',
    messagingSenderId: '253222200495',
    projectId: 'gene-tree-dev-2e250',
    storageBucket: 'gene-tree-dev-2e250.appspot.com',
    iosBundleId: 'com.example.geneTreeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnSLdd940CILXsPpCBV39WQE2wgglfH5k',
    appId: '1:253222200495:web:9289299c6304210261605a',
    messagingSenderId: '253222200495',
    projectId: 'gene-tree-dev-2e250',
    authDomain: 'gene-tree-dev-2e250.firebaseapp.com',
    storageBucket: 'gene-tree-dev-2e250.appspot.com',
    measurementId: 'G-YCWTTC4RPN',
  );
}
